// РЕАЛЬНЫЕ данные с labirintdoors.ru + ФОТО
// Глубокий парсинг: 2025-12-10 18:47:42

export const catalogData = {
  categories: [
    { id: 'all', name: 'Все двери' },
    { id: 'invisible', name: 'Новинки 2025' },
    { id: 'veneer', name: 'Хиты продаж' },
    { id: 'glass', name: 'Белые двери' },
    { id: 'entrance', name: 'Основной каталог' },
    { id: 'thermo', name: 'С терморазрывом' },
  ],

  doors: [
    {
      id: 1,
      name: 'LEOLAB',
      category: 'invisible',
      price: 53900,
      image: '/catalog-images/door_1.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Сталь + утеплитель',
      popular: false,
      new: true
    },
    {
      id: 2,
      name: 'SKYLAB',
      category: 'invisible',
      price: 45300,
      image: '/catalog-images/door_2.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Сталь + утеплитель',
      popular: false,
      new: true
    },
    {
      id: 3,
      name: 'EVOLAB',
      category: 'invisible',
      price: 45300,
      image: '/catalog-images/door_3.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Сталь + утеплитель',
      popular: false,
      new: true
    },
    {
      id: 4,
      name: 'PIANO',
      category: 'veneer',
      price: 43900,
      image: '/catalog-images/door_4.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Шпон премиум',
      popular: true,
      new: false
    },
    {
      id: 5,
      name: 'ROYAL',
      category: 'veneer',
      price: 45300,
      image: '/catalog-images/door_5.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Шпон премиум',
      popular: true,
      new: false
    },
    {
      id: 6,
      name: 'ISSIDA',
      category: 'veneer',
      price: 53900,
      image: '/catalog-images/door_6.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Шпон премиум',
      popular: true,
      new: false
    },
    {
      id: 7,
      name: 'STORM',
      category: 'veneer',
      price: 44500,
      image: '/catalog-images/door_7.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Шпон премиум',
      popular: true,
      new: false
    },
    {
      id: 8,
      name: 'CREDOR',
      category: 'entrance',
      price: 39500,
      image: '/catalog-images/door_8.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Сталь + утеплитель',
      popular: false,
      new: false
    },
    {
      id: 9,
      name: 'KARMINA',
      category: 'entrance',
      price: 38900,
      image: '/catalog-images/door_9.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Сталь + утеплитель',
      popular: false,
      new: false
    },
    {
      id: 10,
      name: 'ACUSTICLAB',
      category: 'entrance',
      price: 46900,
      image: '/catalog-images/door_10.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Сталь + утеплитель',
      popular: false,
      new: false
    },
    {
      id: 11,
      name: 'PLATINUM',
      category: 'entrance',
      price: 42900,
      image: '/catalog-images/door_11.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Сталь + утеплитель',
      popular: false,
      new: false
    },
    {
      id: 12,
      name: 'BETON',
      category: 'entrance',
      price: 41500,
      image: '/catalog-images/door_12.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Сталь + утеплитель',
      popular: false,
      new: false
    },
    {
      id: 13,
      name: 'INFINITY',
      category: 'entrance',
      price: 39500,
      image: '/catalog-images/door_13.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Сталь + утеплитель',
      popular: false,
      new: false
    },
    {
      id: 14,
      name: 'NEW YORK',
      category: 'entrance',
      price: 42500,
      image: '/catalog-images/door_14.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Сталь + утеплитель',
      popular: false,
      new: false
    },
    {
      id: 15,
      name: 'MEGAPOLIS',
      category: 'entrance',
      price: 41900,
      image: '/catalog-images/door_15.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Сталь + утеплитель',
      popular: false,
      new: false
    },
    {
      id: 16,
      name: 'GRAND',
      category: 'entrance',
      price: 44300,
      image: '/catalog-images/door_16.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Сталь + утеплитель',
      popular: false,
      new: false
    },
    {
      id: 17,
      name: 'URBAN',
      category: 'entrance',
      price: 39500,
      image: '/catalog-images/door_17.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Сталь + утеплитель',
      popular: false,
      new: false
    },
    {
      id: 18,
      name: 'ART',
      category: 'entrance',
      price: 37300,
      image: '/catalog-images/door_18.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Сталь + утеплитель',
      popular: false,
      new: false
    },
    {
      id: 19,
      name: 'TRENDO',
      category: 'glass',
      price: 40900,
      image: '/catalog-images/door_19.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Сталь + утеплитель',
      popular: false,
      new: false
    },
    {
      id: 20,
      name: 'VERSAL',
      category: 'glass',
      price: 40900,
      image: '/catalog-images/door_20.jpg',
      features: ["Скрытые петли", "Магнитный замок", "Доводчик", "Звукоизоляция до 42 дБ"],
      acoustic: '42 дБ',
      size: '900×2100 мм',
      material: 'Сталь + утеплитель',
      popular: false,
      new: false
    }
  ]
};
